# Generated by Django 4.0 on 2021-12-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/defaults.png', upload_to='avatars', verbose_name='avatar'),
        ),
    ]
