# Generated by Django 4.0 on 2022-02-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NONE', 'Unset')], default='NONE', max_length=4, verbose_name='Gender'),
        ),
    ]
